import enum

class StepStatus(enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    REVIEW_APPROVED = "REVIEW_APPROVED"
    REVIEW_REJECTED = "REVIEW_REJECTED"

class AgentRole(enum.Enum):
    TECH_LEAD = "TECH_LEAD"
    ARCHITECT = "ARCHITECT"
    FULLSTACK = "FULLSTACK"
    REVIEWER = "REVIEWER"
    DEVOPS = "DEVOPS"
